APP_NAME = 'PI3 - Coleta dados COPA 2022'
API_KEY = 'OqTSIEJVhjUo19vmhQun89uvw'
API_KEY_SECRET = '6l3KQiyIXdilcd78NvLFpP5AVxMBuSGcdADYDy3TB5t0vhWfm7'
ACCESS_TOKEN = '1569361678621360130-9HcHhb6jErLRPMWU0pxdVa62FH9ppl'
ACCESS_TOKEN_SECRET = 'Jyck2A9p5XyAPBSEKpZQflcFk6cYhWeQ1BXoa7obPsEt9'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAALYJhAEAAAAAX5I3CychGxZpDocq%2FxcGYstw7kk%3Dfl2A5Om5L01SptaZ0LhCQtW1UYure1KML8VbJ85B1ag1d3Dtlh'
